[sqs]
  region = "us-east-1"
  project = "Mola"
  app = "Test"
  service = "Demo"

[redis]
  addr = "redis.test.local:6379"
  password = ""
  db = 0
[logs]
  console_level = "debug"
  format = ""
  [logs.rotate]
    link = "./applicationServer.log"
    file = "./applicationServer.log.%Y%m%d%H%M"
    rotation = 24
    keep_rotation = 7


[[orders]]
  name = "DemoOrder1"
  timeout = 180
  retry = 3

