// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mola.proto

package mola

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderBrief_State int32

const (
	OrderBrief_UNKNOWN    OrderBrief_State = 0
	OrderBrief_SUCCEED    OrderBrief_State = 1
	OrderBrief_FAILED     OrderBrief_State = 2
	OrderBrief_TIMEOUT    OrderBrief_State = 3
	OrderBrief_DUPLICATED OrderBrief_State = 4
)

var OrderBrief_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCEED",
	2: "FAILED",
	3: "TIMEOUT",
	4: "DUPLICATED",
}

var OrderBrief_State_value = map[string]int32{
	"UNKNOWN":    0,
	"SUCCEED":    1,
	"FAILED":     2,
	"TIMEOUT":    3,
	"DUPLICATED": 4,
}

func (x OrderBrief_State) String() string {
	return proto.EnumName(OrderBrief_State_name, int32(x))
}

func (OrderBrief_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_859920baff70f664, []int{2, 0}
}

type OrderEnvelop struct {
	App                  string   `protobuf:"bytes,1,opt,name=App,proto3" json:"App,omitempty"`
	Contract             string   `protobuf:"bytes,2,opt,name=Contract,proto3" json:"Contract,omitempty"`
	TraceID              string   `protobuf:"bytes,3,opt,name=TraceID,proto3" json:"TraceID,omitempty"`
	OrderType            string   `protobuf:"bytes,4,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderEnvelop) Reset()         { *m = OrderEnvelop{} }
func (m *OrderEnvelop) String() string { return proto.CompactTextString(m) }
func (*OrderEnvelop) ProtoMessage()    {}
func (*OrderEnvelop) Descriptor() ([]byte, []int) {
	return fileDescriptor_859920baff70f664, []int{0}
}

func (m *OrderEnvelop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderEnvelop.Unmarshal(m, b)
}
func (m *OrderEnvelop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderEnvelop.Marshal(b, m, deterministic)
}
func (m *OrderEnvelop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderEnvelop.Merge(m, src)
}
func (m *OrderEnvelop) XXX_Size() int {
	return xxx_messageInfo_OrderEnvelop.Size(m)
}
func (m *OrderEnvelop) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderEnvelop.DiscardUnknown(m)
}

var xxx_messageInfo_OrderEnvelop proto.InternalMessageInfo

func (m *OrderEnvelop) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *OrderEnvelop) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *OrderEnvelop) GetTraceID() string {
	if m != nil {
		return m.TraceID
	}
	return ""
}

func (m *OrderEnvelop) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

type OrderMessage struct {
	Envelop              *OrderEnvelop `protobuf:"bytes,1,opt,name=Envelop,proto3" json:"Envelop,omitempty"`
	WorkerConf           *any.Any      `protobuf:"bytes,2,opt,name=WorkerConf,proto3" json:"WorkerConf,omitempty"`
	Body                 *any.Any      `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderMessage) Reset()         { *m = OrderMessage{} }
func (m *OrderMessage) String() string { return proto.CompactTextString(m) }
func (*OrderMessage) ProtoMessage()    {}
func (*OrderMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_859920baff70f664, []int{1}
}

func (m *OrderMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMessage.Unmarshal(m, b)
}
func (m *OrderMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMessage.Marshal(b, m, deterministic)
}
func (m *OrderMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMessage.Merge(m, src)
}
func (m *OrderMessage) XXX_Size() int {
	return xxx_messageInfo_OrderMessage.Size(m)
}
func (m *OrderMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMessage proto.InternalMessageInfo

func (m *OrderMessage) GetEnvelop() *OrderEnvelop {
	if m != nil {
		return m.Envelop
	}
	return nil
}

func (m *OrderMessage) GetWorkerConf() *any.Any {
	if m != nil {
		return m.WorkerConf
	}
	return nil
}

func (m *OrderMessage) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

// OrderBrief to send order process brief to data application
type OrderBrief struct {
	Envelop              *OrderEnvelop    `protobuf:"bytes,1,opt,name=Envelop,proto3" json:"Envelop,omitempty"`
	Result               OrderBrief_State `protobuf:"varint,2,opt,name=Result,proto3,enum=mola.OrderBrief_State" json:"Result,omitempty"`
	Duration             float64          `protobuf:"fixed64,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
	ErrorMessage         string           `protobuf:"bytes,4,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	CustomRes            string           `protobuf:"bytes,5,opt,name=CustomRes,proto3" json:"CustomRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderBrief) Reset()         { *m = OrderBrief{} }
func (m *OrderBrief) String() string { return proto.CompactTextString(m) }
func (*OrderBrief) ProtoMessage()    {}
func (*OrderBrief) Descriptor() ([]byte, []int) {
	return fileDescriptor_859920baff70f664, []int{2}
}

func (m *OrderBrief) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBrief.Unmarshal(m, b)
}
func (m *OrderBrief) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBrief.Marshal(b, m, deterministic)
}
func (m *OrderBrief) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBrief.Merge(m, src)
}
func (m *OrderBrief) XXX_Size() int {
	return xxx_messageInfo_OrderBrief.Size(m)
}
func (m *OrderBrief) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBrief.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBrief proto.InternalMessageInfo

func (m *OrderBrief) GetEnvelop() *OrderEnvelop {
	if m != nil {
		return m.Envelop
	}
	return nil
}

func (m *OrderBrief) GetResult() OrderBrief_State {
	if m != nil {
		return m.Result
	}
	return OrderBrief_UNKNOWN
}

func (m *OrderBrief) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *OrderBrief) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *OrderBrief) GetCustomRes() string {
	if m != nil {
		return m.CustomRes
	}
	return ""
}

func init() {
	proto.RegisterEnum("mola.OrderBrief_State", OrderBrief_State_name, OrderBrief_State_value)
	proto.RegisterType((*OrderEnvelop)(nil), "mola.OrderEnvelop")
	proto.RegisterType((*OrderMessage)(nil), "mola.OrderMessage")
	proto.RegisterType((*OrderBrief)(nil), "mola.OrderBrief")
}

func init() { proto.RegisterFile("mola.proto", fileDescriptor_859920baff70f664) }

var fileDescriptor_859920baff70f664 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x7c, 0xca, 0x40, 0x4c, 0xb3, 0x31, 0xa6, 0x12, 0x0f, 0xa6, 0x27, 0x0e, 0x66, 0x49,
	0xd0, 0x8b, 0x47, 0x68, 0x6b, 0x42, 0x14, 0x48, 0x96, 0x12, 0xce, 0x0b, 0x2c, 0x84, 0x58, 0xba,
	0xcd, 0x76, 0x6b, 0xd2, 0xb3, 0x7f, 0xc3, 0x1f, 0x6b, 0x3a, 0x6d, 0xb1, 0x1e, 0x3c, 0x78, 0x9b,
	0x79, 0xef, 0x65, 0xde, 0x9b, 0x07, 0x70, 0x92, 0x01, 0xa7, 0x91, 0x92, 0x5a, 0x92, 0x46, 0x36,
	0xf7, 0x6f, 0x0f, 0x52, 0x1e, 0x02, 0x31, 0x44, 0x6c, 0x93, 0xec, 0x87, 0x3c, 0x4c, 0x73, 0x81,
	0xad, 0xa1, 0xb7, 0x50, 0x3b, 0xa1, 0xbc, 0xf0, 0x43, 0x04, 0x32, 0x22, 0x26, 0xd4, 0xc7, 0x51,
	0x64, 0x19, 0xf7, 0xc6, 0xa0, 0xc3, 0xb2, 0x91, 0xf4, 0xe1, 0xd2, 0x91, 0xa1, 0x56, 0x7c, 0xab,
	0xad, 0x1a, 0xc2, 0xe7, 0x9d, 0x58, 0xd0, 0xf6, 0x15, 0xdf, 0x8a, 0xa9, 0x6b, 0xd5, 0x91, 0x2a,
	0x57, 0x72, 0x07, 0x1d, 0xbc, 0xeb, 0xa7, 0x91, 0xb0, 0x1a, 0xc8, 0xfd, 0x00, 0xf6, 0x97, 0x51,
	0xd8, 0xce, 0x44, 0x1c, 0xf3, 0x83, 0x20, 0x0f, 0xd0, 0x2e, 0x12, 0xa0, 0x75, 0x77, 0x44, 0x28,
	0x7e, 0x51, 0xcd, 0xc6, 0x4a, 0x09, 0x79, 0x02, 0x58, 0x4b, 0xf5, 0x2e, 0x94, 0x23, 0xc3, 0x3d,
	0x86, 0xea, 0x8e, 0xae, 0x69, 0xfe, 0x24, 0x2d, 0x9f, 0xa4, 0xe3, 0x30, 0x65, 0x15, 0x1d, 0x19,
	0x40, 0x63, 0x22, 0x77, 0x29, 0x26, 0xfd, 0x4b, 0x8f, 0x0a, 0xfb, 0xb3, 0x06, 0x80, 0xce, 0x13,
	0x75, 0x14, 0xfb, 0x7f, 0x86, 0xa3, 0xd0, 0x62, 0x22, 0x4e, 0x82, 0xbc, 0xad, 0xab, 0xd1, 0x4d,
	0x45, 0x8c, 0xf7, 0xe8, 0x52, 0x73, 0x2d, 0x58, 0xa1, 0xca, 0xfa, 0x75, 0x13, 0xc5, 0xf5, 0x51,
	0x86, 0x18, 0xcd, 0x60, 0xe7, 0x9d, 0xd8, 0xd0, 0xf3, 0x94, 0x92, 0x65, 0x4d, 0x45, 0x91, 0xbf,
	0xb0, 0xac, 0x69, 0x27, 0x89, 0xb5, 0x3c, 0x31, 0x11, 0x5b, 0xcd, 0xbc, 0xe9, 0x33, 0x60, 0x3f,
	0x43, 0x13, 0xed, 0x08, 0x40, 0x6b, 0x35, 0x7f, 0x5d, 0xac, 0xe7, 0xe6, 0x05, 0xe9, 0x42, 0x7b,
	0xb9, 0x72, 0x1c, 0xcf, 0x73, 0x4d, 0x23, 0x23, 0x5e, 0xc6, 0xd3, 0x37, 0xcf, 0x35, 0x6b, 0x19,
	0xe1, 0x4f, 0x67, 0xde, 0x62, 0xe5, 0x9b, 0xf5, 0x4d, 0x0b, 0x9b, 0x79, 0xfc, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x03, 0xe6, 0xd0, 0xf2, 0x50, 0x02, 0x00, 0x00,
}
