// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DemoConf struct {
	ConfItem1            string   `protobuf:"bytes,1,opt,name=ConfItem1,proto3" json:"ConfItem1,omitempty"`
	ConfItem2            int64    `protobuf:"varint,2,opt,name=ConfItem2,proto3" json:"ConfItem2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoConf) Reset()         { *m = DemoConf{} }
func (m *DemoConf) String() string { return proto.CompactTextString(m) }
func (*DemoConf) ProtoMessage()    {}
func (*DemoConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *DemoConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoConf.Unmarshal(m, b)
}
func (m *DemoConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoConf.Marshal(b, m, deterministic)
}
func (m *DemoConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoConf.Merge(m, src)
}
func (m *DemoConf) XXX_Size() int {
	return xxx_messageInfo_DemoConf.Size(m)
}
func (m *DemoConf) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoConf.DiscardUnknown(m)
}

var xxx_messageInfo_DemoConf proto.InternalMessageInfo

func (m *DemoConf) GetConfItem1() string {
	if m != nil {
		return m.ConfItem1
	}
	return ""
}

func (m *DemoConf) GetConfItem2() int64 {
	if m != nil {
		return m.ConfItem2
	}
	return 0
}

type DemoOrder struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  string   `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoOrder) Reset()         { *m = DemoOrder{} }
func (m *DemoOrder) String() string { return proto.CompactTextString(m) }
func (*DemoOrder) ProtoMessage()    {}
func (*DemoOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *DemoOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoOrder.Unmarshal(m, b)
}
func (m *DemoOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoOrder.Marshal(b, m, deterministic)
}
func (m *DemoOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoOrder.Merge(m, src)
}
func (m *DemoOrder) XXX_Size() int {
	return xxx_messageInfo_DemoOrder.Size(m)
}
func (m *DemoOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DemoOrder proto.InternalMessageInfo

func (m *DemoOrder) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *DemoOrder) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoConf)(nil), "demo.DemoConf")
	proto.RegisterType((*DemoOrder)(nil), "demo.DemoOrder")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xdc, 0xb8, 0x38, 0x5c, 0x52,
	0x73, 0xf3, 0x9d, 0xf3, 0xf3, 0xd2, 0x84, 0x64, 0xb8, 0x38, 0x41, 0xb4, 0x67, 0x49, 0x6a, 0xae,
	0xa1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x42, 0x00, 0x59, 0xd6, 0x48, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x19, 0x21, 0x6b, 0xa4, 0xa4, 0xcf, 0xc5, 0x09, 0x32, 0xc7, 0xbf, 0x28, 0x25, 0xb5,
	0x48, 0x48, 0x80, 0x8b, 0x39, 0x2d, 0x3f, 0x1f, 0x6a, 0x04, 0x88, 0x09, 0x12, 0x49, 0x4a, 0x2c,
	0x02, 0x6b, 0xe3, 0x0c, 0x02, 0x31, 0x93, 0xd8, 0xc0, 0xae, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x6a, 0x27, 0xb3, 0x2a, 0x93, 0x00, 0x00, 0x00,
}
